--[[

    Please do NOT edit this file but go to http://wow.curseforge.com/addons/armory/localization/ instead.
    
    The contents of this file will be generated automatically.
    
]]--

local L = LibStub("AceLocale-3.0"):NewLocale("ArmoryGuildBank", "esMX");
if ( not L ) then 
    return;
end

L["ARMORY_CMD_DELETE_GUILD"] = "Banco de la Hermandad" -- Needs review
L["ARMORY_CMD_DELETE_GUILD_MSG"] = "Banco de la Hermandad de '%1$s' en el reino '%2$s' ha sido removido." -- Needs review
L["ARMORY_CMD_DELETE_GUILD_NOT_FOUND"] = "Banco de la Hermandad de '%1$s'en el reino '%2$s' no ha sido encontrado!" -- Needs review
L["ARMORY_CMD_DELETE_GUILD_PARAMS_TEXT"] = " [hermandad] [reino] " -- Needs review
L["ARMORY_CMD_DELETE_GUILD_TEXT"] = "Borrar Banco de Hermandad" -- Needs review
L["ARMORY_CMD_GUILDBANK"] = "Banco de Hermandad|bh" -- Needs review
L["ARMORY_CMD_GUILDBANK_MENUTEXT"] = "Ocultar Banco de Hermandad" -- Needs review
L["ARMORY_CMD_GUILDBANK_TEXT"] = "Alterna el Banco de Hermandad habilitado o deshabilitado" -- Needs review
L["ARMORY_CMD_SET_AGBCOUNTALL_MENUTEXT"] = "Incluir todos los reinos en la cuenta" -- Needs review
L["ARMORY_CMD_SET_AGBCOUNTALL_TEXT"] = "Incluye cuenta de objeto para todos los reinos" -- Needs review
L["ARMORY_CMD_SET_AGBCOUNTALL_TOOLTIP"] = "Si esta habilitado, los totales en el banco de hermandad se muestra para todos los reinos; de otra manera solo para el reino actual." -- Needs review
L["ARMORY_CMD_SET_AGBCOUNTMYGUILD_MENUTEXT"] = "Include current guild only" -- Requires localization
L["ARMORY_CMD_SET_AGBCOUNTMYGUILD_TEXT"] = "include item counts for the current guild only" -- Requires localization
L["ARMORY_CMD_SET_AGBCOUNTMYGUILD_TOOLTIP"] = "If enabled, Guild Bank totals are shown for the current and selected character's guild only." -- Requires localization
L["ARMORY_CMD_SET_AGBCOUNTXFACTION_MENUTEXT"] = "Include all factions in counts" -- Requires localization
L["ARMORY_CMD_SET_AGBCOUNTXFACTION_TEXT"] = "include item counts for all factions" -- Requires localization
L["ARMORY_CMD_SET_AGBCOUNTXFACTION_TOOLTIP"] = "If enabled, Guild Bank totals are shown for all factions; otherwise only for the current faction." -- Requires localization
L["ARMORY_CMD_SET_AGBFIND_MENUTEXT"] = "incluir en '/ar buscar objeto|todos'" -- Needs review
L["ARMORY_CMD_SET_AGBFIND_TEXT"] = "Incluir cuando se buscas objetos" -- Needs review
L["ARMORY_CMD_SET_AGBFIND_TOOLTIP"] = "If enabled, the Guild Bank will also be searched when performing a database lookup with '/ar find item|all'." -- Requires localization
L["ARMORY_CMD_SET_AGBINTEGRATE_MENUTEXT"] = "Integrate with inventory" -- Requires localization
L["ARMORY_CMD_SET_AGBINTEGRATE_TEXT"] = "integrate with Armory's inventory" -- Requires localization
L["ARMORY_CMD_SET_AGBINTEGRATE_TOOLTIP"] = "If enabled, the selected character's Guild Bank will be added as an extra tab in the inventory sheet." -- Requires localization
L["ARMORY_CMD_SET_AGBITEMCOUNT_MENUTEXT"] = "Show tooltip item counts" -- Requires localization
L["ARMORY_CMD_SET_AGBITEMCOUNT_TEXT"] = "show item counts in tooltips" -- Requires localization
L["ARMORY_CMD_SET_AGBITEMCOUNT_TOOLTIP"] = "If enabled, item tooltips will show Guild Bank totals." -- Requires localization
L["ARMORY_CMD_SET_AGBUNICOLOR_MENUTEXT"] = "Use Armory's color" -- Requires localization
L["ARMORY_CMD_SET_AGBUNICOLOR_TEXT"] = "link to Armory's item count color" -- Requires localization
L["ARMORY_CMD_SET_AGBUNICOLOR_TOOLTIP"] = "If enabled, the same color will be used for all item counts shown in tooltips." -- Requires localization
L["ARMORY_GUILDBANK_ABORTING"] = "Aborting..." -- Requires localization
L["ARMORY_GUILDBANK_NO_DATA"] = "There is no Guild Bank data available." -- Requires localization
L["ARMORY_GUILDBANK_NO_TABS"] = "Please visit the bank and open all tabs..." -- Requires localization
L["ARMORY_GUILDBANK_SUBTEXT"] = "These options allow you to modify Armory Guild Bank's behavior." -- Requires localization
L["ARMORY_GUILDBANK_TITLE"] = "Guild Bank" -- Requires localization
L["BINDING_NAME_ARMORYGUILDBANK_TOGGLE"] = "Toggle Armory Guild Bank" -- Requires localization

